=== json-schema-org/JSON-Schema-Test-Suite/validation-test-schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://json-schema.org/tests/validation-test-schema",
    "description": "A schema for files contained within the unified validation/ test suite",

    "type": "array",
    "minItems": 1,
    "items": {
        "description": "An individual test case, containing multiple tests of a single schema's behavior across dialects",

        "type": "object",
        "required": [ "description", "compatibility", "schema", "tests" ],
        "properties": {
            "description": {
                "description": "The test case description",
                "type": "string"
            },
            "comment": {
                "description": "Any additional comments about the test case",
                "type": "string"
            },
            "compatibility": {
                "description": "Dialect constraint for this test case. A bare number means 'that dialect and above' (minimum). Prefix with '=' for an exact match or '<=' for a maximum. Combine with commas for a range, e.g. '6,<=2019'. Valid dialect tokens: 3, 4, 6, 7, 2019, 2020.",
                "type": "string",
                "pattern": "^(<=|=)?([0-9]+)(,(<=|=)?([0-9]+))*$"
            },
            "schema": {
                "description": "A valid JSON Schema, written without a $schema keyword so it stays dialect-agnostic. The applicable dialects are expressed via the compatibility field."
            },
            "tests": {
                "description": "A set of related tests all using the same schema",
                "type": "array",
                "items": { "$ref": "#/$defs/test" },
                "minItems": 1
            },
            "specification":{
                "description": "A reference to a specification document which defines the behavior tested by this test case. Typically this should be a JSON Schema specification document, though in cases where the JSON Schema specification points to another RFC it should contain *both* the portion of the JSON Schema specification which indicates what RFC (and section) to follow as *well* as information on where in that specification the behavior is specified.",

                "type": "array",
                "minItems": 1,
                "uniqueItems": true,
                "items": {
                    "properties": {
                        "core": { 
                            "description": "A section in official JSON Schema core drafts",
                            "url": "https://json-schema.org/specification-links",
                            "pattern": "^[0-9a-zA-Z]+(\\.[0-9a-zA-Z]+)*$", 
                            "type":"string"
                        },
                        "validation": {
                            "description": "A section in official JSON Schema validation drafts",
                            "url": "https://json-schema.org/specification-links",
                            "pattern": "^[0-9a-zA-Z]+(\\.[0-9a-zA-Z]+)*$", 
                            "type":"string" 
                        },
                        "ecma262": { 
                            "description": "A section in official ECMA 262 specification for defining regular expressions",
                            "url": "https://262.ecma-international.org/",
                            "pattern": "^[0-9a-zA-Z]+(\\.[0-9a-zA-Z]+)*$", 
                            "type":"string" 
                        },
                        "perl5": { 
                            "description": "A section name in Perl documentation for defining regular expressions",
                            "url": "https://perldoc.perl.org/perlre",
                            "type":"string" 
                        },
                        "quote": { 
                            "description": "Quote describing the test case",
                            "type":"string" 
                        }
                    },
                    "patternProperties": {
                        "^rfc\\d+$": { 
                            "description": "A section in official RFC for the given rfc number",
                            "url": "https://www.rfc-editor.org/",
                            "pattern": "^[0-9a-zA-Z]+(\\.[0-9a-zA-Z]+)*$", 
                            "type":"string" 
                        },
                        "^iso\\d+$": { 
                            "description": "A section in official ISO for the given iso number",
                            "pattern": "^[0-9a-zA-Z]+(\\.[0-9a-zA-Z]+)*$", 
                            "type": "string" 
                        }
                    },
                    "additionalProperties": { "type": "string" },
                    "minProperties": 1,
                    "propertyNames": {
                        "oneOf": [
                            {
                                "pattern": "^((iso)|(rfc))[0-9]+$"
                            },
                            {
                                "enum": [ "core", "validation", "ecma262", "perl5", "quote" ]
                            }
                        ]
                    }
                }
            }
        },
        "additionalProperties": false
    },

    "$defs": {
        "test": {
            "description": "A single test",

            "type": "object",
            "required": [ "description", "data", "valid" ],
            "properties": {
                "description": {
                    "description": "The test description, briefly explaining which behavior it exercises",
                    "type": "string"
                },
                "comment": {
                    "description": "Any additional comments about the test",
                    "type": "string"
                },
                "data": {
                    "description": "The instance which should be validated against the schema in \"schema\"."
                },
                "valid": {
                    "description": "Whether the validation process of this instance should consider the instance valid or not",
                    "type": "boolean"
                }
            },
            "additionalProperties": false
        }
    }
}

=== json-schema-org/JSON-Schema-Test-Suite/tests/v1/exclusiveMaximum.json
[
    {
        "description": "exclusiveMaximum validation",
        "compatibility": "6",
        "schema": {
            "$schema": "https://json-schema.org/v1",
            "exclusiveMaximum": 3.0
        },
        "tests": [
            {
                "description": "below the exclusiveMaximum is valid",
                "data": 2.2,
                "valid": true
            },
            {
                "description": "boundary point is invalid",
                "data": 3.0,
                "valid": false
            },
            {
                "description": "above the exclusiveMaximum is invalid",
                "data": 3.5,
                "valid": false
            },
            {
                "description": "ignores non-numbers",
                "data": "x",
                "valid": true
            }
        ]
    }
]

=== json-schema-org/JSON-Schema-Test-Suite/tests/v1/contains.json
[
    {
        "description": "contains keyword validation",
        "compatibility": "6",
        "schema": {
            "$schema": "https://json-schema.org/v1",
            "contains": {
                "minimum": 5
            }
        },
        "tests": [
            {
                "description": "array with item matching schema (5) is valid",
                "data": [
                    3,
                    4,
                    5
                ],
                "valid": true
            },
            {
                "description": "array with item matching schema (6) is valid",
                "data": [
                    3,
                    4,
                    6
                ],
                "valid": true
            },
            {
                "description": "array with two items matching schema (5, 6) is valid",
                "data": [
                    3,
                    4,
                    5,
                    6
                ],
                "valid": true
            },
            {
                "description": "array without items matching schema is invalid",
                "data": [
                    2,
                    3,
                    4
                ],
                "valid": false
            },
            {
                "description": "empty array is invalid",
                "data": [],
                "valid": false
            },
            {
                "description": "not array or object is valid",
                "data": 42,
                "valid": true
            }
        ]
    },
    {
        "description": "contains keyword with const keyword",
        "compatibility": "6",
        "schema": {
            "$schema": "https://json-schema.org/v1",
            "contains": {
                "const": 5
            }
        },
        "tests": [
            {
                "description": "array with item 5 is valid",
                "data": [
                    3,
                    4,
                    5
                ],
                "valid": true
            },
            {
                "description": "array with two items 5 is valid",
                "data": [
                    3,
                    4,
                    5,
                    5
                ],
                "valid": true
            },
            {
                "description": "array without item 5 is invalid",
                "data": [
                    1,
                    2,
                    3,
                    4
                ],
                "valid": false
            }
        ]
    },
    {
        "description": "contains keyword with boolean schema true",
        "compatibility": "6",
        "schema": {
            "$schema": "https://json-schema.org/v1",
            "contains": true
        },
        "tests": [
            {
                "description": "any non-empty array is valid",
                "data": [
                    "foo"
                ],
                "valid": true
            },
            {
                "description": "empty array is invalid",
                "data": [],
                "valid": false
            }
        ]
    },
    {
        "description": "contains keyword with boolean schema false",
        "compatibility": "6",
        "schema": {
            "$schema": "https://json-schema.org/v1",
            "contains": false
        },
        "tests": [
            {
                "description": "any non-empty array is invalid",
                "data": [
                    "foo"
                ],
                "valid": false
            },
            {
                "description": "empty array is invalid",
                "data": [],
                "valid": false
            },
            {
                "description": "non-arrays are valid - string",
                "data": "contains does not apply to strings",
                "valid": true
            },
            {
                "description": "non-arrays are valid - object",
                "data": {},
                "valid": true
            },
            {
                "description": "non-arrays are valid - number",
                "data": 42,
                "valid": true
            },
            {
                "description": "non-arrays are valid - boolean",
                "data": false,
                "valid": true
            },
            {
                "description": "non-arrays are valid - null",
                "data": null,
                "valid": true
            }
        ]
    },
    {
        "description": "items + contains",
        "compatibility": "6",
        "schema": {
            "$schema": "https://json-schema.org/v1",
            "additionalProperties": {
                "multipleOf": 2
            },
            "items": {
                "multipleOf": 2
            },
            "contains": {
                "multipleOf": 3
            }
        },
        "tests": [
            {
                "description": "matches items, does not match contains",
                "data": [
                    2,
                    4,
                    8
                ],
                "valid": false
            },
            {
                "description": "does not match items, matches contains",
                "data": [
                    3,
                    6,
                    9
                ],
                "valid": false
            },
            {
                "description": "matches both items and contains",
                "data": [
                    6,
                    12
                ],
                "valid": true
            },
            {
                "description": "matches neither items nor contains",
                "data": [
                    1,
                    5
                ],
                "valid": false
            }
        ]
    },
    {
        "description": "contains with false if subschema",
        "compatibility": "7",
        "schema": {
            "$schema": "https://json-schema.org/v1",
            "contains": {
                "if": false,
                "else": true
            }
        },
        "tests": [
            {
                "description": "any non-empty array is valid",
                "data": [
                    "foo"
                ],
                "valid": true
            },
            {
                "description": "empty array is invalid",
                "data": [],
                "valid": false
            }
        ]
    },
    {
        "description": "contains with null instance elements",
        "compatibility": "6",
        "schema": {
            "$schema": "https://json-schema.org/v1",
            "contains": {
                "type": "null"
            }
        },
        "tests": [
            {
                "description": "allows null items",
                "data": [
                    null
                ],
                "valid": true
            }
        ]
    }
]

=== json-schema-org/JSON-Schema-Test-Suite/tests/v1/format/uri-template.json
[
    {
        "description": "format: uri-template",
        "compatibility": "6",
        "schema": {
            "$schema": "https://json-schema.org/v1",
            "format": "uri-template"
        },
        "tests": [
            {
                "description": "all string formats ignore integers",
                "data": 12,
                "valid": true
            },
            {
                "description": "all string formats ignore floats",
                "data": 13.7,
                "valid": true
            },
            {
                "description": "all string formats ignore objects",
                "data": {},
                "valid": true
            },
            {
                "description": "all string formats ignore arrays",
                "data": [],
                "valid": true
            },
            {
                "description": "all string formats ignore booleans",
                "data": false,
                "valid": true
            },
            {
                "description": "all string formats ignore nulls",
                "data": null,
                "valid": true
            },
            {
                "description": "a valid uri-template",
                "data": "http://example.com/dictionary/{term:1}/{term}",
                "valid": true
            },
            {
                "description": "an invalid uri-template",
                "data": "http://example.com/dictionary/{term:1}/{term",
                "valid": false
            },
            {
                "description": "a valid uri-template without variables",
                "data": "http://example.com/dictionary",
                "valid": true
            },
            {
                "description": "a valid relative uri-template",
                "data": "dictionary/{term:1}/{term}",
                "valid": true
            }
        ]
    }
]

=== json-schema-org/JSON-Schema-Test-Suite/tests/v1/propertyNames.json
[
    {
        "description": "propertyNames validation",
        "compatibility": "6",
        "schema": {
            "$schema": "https://json-schema.org/v1",
            "propertyNames": {
                "maxLength": 3
            }
        },
        "tests": [
            {
                "description": "all property names valid",
                "data": {
                    "f": {},
                    "foo": {}
                },
                "valid": true
            },
            {
                "description": "some property names invalid",
                "data": {
                    "foo": {},
                    "foobar": {}
                },
                "valid": false
            },
            {
                "description": "object without properties is valid",
                "data": {},
                "valid": true
            },
            {
                "description": "ignores arrays",
                "data": [
                    1,
                    2,
                    3,
                    4
                ],
                "valid": true
            },
            {
                "description": "ignores strings",
                "data": "foobar",
                "valid": true
            },
            {
                "description": "ignores other non-objects",
                "data": 12,
                "valid": true
            }
        ]
    },
    {
        "description": "propertyNames with boolean schema true",
        "compatibility": "6",
        "schema": {
            "$schema": "https://json-schema.org/v1",
            "propertyNames": true
        },
        "tests": [
            {
                "description": "object with any properties is valid",
                "data": {
                    "foo": 1
                },
                "valid": true
            },
            {
                "description": "empty object is valid",
                "data": {},
                "valid": true
            }
        ]
    },
    {
        "description": "propertyNames with boolean schema false",
        "compatibility": "6",
        "schema": {
            "$schema": "https://json-schema.org/v1",
            "propertyNames": false
        },
        "tests": [
            {
                "description": "object with any properties is invalid",
                "data": {
                    "foo": 1
                },
                "valid": false
            },
            {
                "description": "empty object is valid",
                "data": {},
                "valid": true
            }
        ]
    }
]

=== json-schema-org/JSON-Schema-Test-Suite/tests/v1/optional/id.json
[
    {
        "description": "$id inside an enum is not a real identifier",
        "compatibility": "2019",
        "comment": "the implementation must not be confused by an $id buried in the enum",
        "schema": {
            "$schema": "https://json-schema.org/v1",
            "$defs": {
                "id_in_enum": {
                    "enum": [
                        {
                            "$id": "https://localhost:1234/v1/id/my_identifier.json",
                            "type": "null"
                        }
                    ]
                },
                "real_id_in_schema": {
                    "$id": "https://localhost:1234/v1/id/my_identifier.json",
                    "type": "string"
                },
                "zzz_id_in_const": {
                    "const": {
                        "$id": "https://localhost:1234/v1/id/my_identifier.json",
                        "type": "null"
                    }
                }
            },
            "anyOf": [
                {
                    "$ref": "#/$defs/id_in_enum"
                },
                {
                    "$ref": "https://localhost:1234/v1/id/my_identifier.json"
                }
            ]
        },
        "tests": [
            {
                "description": "exact match to enum, and type matches",
                "data": {
                    "$id": "https://localhost:1234/v1/id/my_identifier.json",
                    "type": "null"
                },
                "valid": true
            },
            {
                "description": "match $ref to $id",
                "data": "a string to match #/$defs/id_in_enum",
                "valid": true
            },
            {
                "description": "no match on enum or $ref to $id",
                "data": 1,
                "valid": false
            }
        ]
    }
]

=== json-schema-org/JSON-Schema-Test-Suite/tests/v1/format/iri-reference.json
[
    {
        "description": "validation of IRI References",
        "compatibility": "7",
        "schema": {
            "$schema": "https://json-schema.org/v1",
            "format": "iri-reference"
        },
        "tests": [
            {
                "description": "all string formats ignore integers",
                "data": 12,
                "valid": true
            },
            {
                "description": "all string formats ignore floats",
                "data": 13.7,
                "valid": true
            },
            {
                "description": "all string formats ignore objects",
                "data": {},
                "valid": true
            },
            {
                "description": "all string formats ignore arrays",
                "data": [],
                "valid": true
            },
            {
                "description": "all string formats ignore booleans",
                "data": false,
                "valid": true
            },
            {
                "description": "all string formats ignore nulls",
                "data": null,
                "valid": true
            },
            {
                "description": "a valid IRI",
                "data": "http://ƒøø.ßår/?∂éœ=πîx#πîüx",
                "valid": true
            },
            {
                "description": "a valid protocol-relative IRI Reference",
                "data": "//ƒøø.ßår/?∂éœ=πîx#πîüx",
                "valid": true
            },
            {
                "description": "a valid relative IRI Reference",
                "data": "/âππ",
                "valid": true
            },
            {
                "description": "an invalid IRI Reference",
                "data": "\\\\WINDOWS\\filëßåré",
                "valid": false
            },
            {
                "description": "a valid IRI Reference",
                "data": "âππ",
                "valid": true
            },
            {
                "description": "a valid IRI fragment",
                "data": "#ƒrägmênt",
                "valid": true
            },
            {
                "description": "an invalid IRI fragment",
                "data": "#ƒräg\\mênt",
                "valid": false
            }
        ]
    }
]

=== json-schema-org/JSON-Schema-Test-Suite/validation/tests/maxLength.json
[
    {
        "description": "maxLength validation",
        "compatibility": "3",
        "schema": {"maxLength": 2},
        "tests": [
            {
                "description": "shorter is valid",
                "data": "f",
                "valid": true
            },
            {
                "description": "exact length is valid",
                "data": "fo",
                "valid": true
            },
            {
                "description": "too long is invalid",
                "data": "foo",
                "valid": false
            },
            {
                "description": "ignores non-strings",
                "data": 100,
                "valid": true
            },
            {
                "description": "two graphemes is long enough",
                "data": "\uD83D\uDCA9\uD83D\uDCA9",
                "valid": true
            }
        ]
    },
    {
        "description": "maxLength validation with a decimal",
        "compatibility": "6",
        "schema": {"maxLength": 2.0},
        "tests": [
            {
                "description": "shorter is valid",
                "data": "f",
                "valid": true
            },
            {
                "description": "too long is invalid",
                "data": "foo",
                "valid": false
            }
        ]
    }
]

=== json-schema-org/JSON-Schema-Test-Suite/tests/v1/anchor.json
[
    {
        "description": "Location-independent identifier",
        "compatibility": "2019",
        "schema": {
            "$schema": "https://json-schema.org/v1",
            "$ref": "#foo",
            "$defs": {
                "A": {
                    "$anchor": "foo",
                    "type": "integer"
                }
            }
        },
        "tests": [
            {
                "data": 1,
                "description": "match",
                "valid": true
            },
            {
                "data": "a",
                "description": "mismatch",
                "valid": false
            }
        ]
    },
    {
        "description": "Location-independent identifier with absolute URI",
        "compatibility": "2019",
        "schema": {
            "$schema": "https://json-schema.org/v1",
            "$ref": "http://localhost:1234/v1/bar#foo",
            "$defs": {
                "A": {
                    "$id": "http://localhost:1234/v1/bar",
                    "$anchor": "foo",
                    "type": "integer"
                }
            }
        },
        "tests": [
            {
                "data": 1,
                "description": "match",
                "valid": true
            },
            {
                "data": "a",
                "description": "mismatch",
                "valid": false
            }
        ]
    },
    {
        "description": "Location-independent identifier with base URI change in subschema",
        "compatibility": "2019",
        "schema": {
            "$schema": "https://json-schema.org/v1",
            "$id": "http://localhost:1234/v1/root",
            "$ref": "http://localhost:1234/v1/nested.json#foo",
            "$defs": {
                "A": {
                    "$id": "nested.json",
                    "$defs": {
                        "B": {
                            "$anchor": "foo",
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "tests": [
            {
                "data": 1,
                "description": "match",
                "valid": true
            },
            {
                "data": "a",
                "description": "mismatch",
                "valid": false
            }
        ]
    },
    {
        "description": "same $anchor with different base uri",
        "compatibility": "2019",
        "schema": {
            "$schema": "https://json-schema.org/v1",
            "$id": "http://localhost:1234/v1/foobar",
            "$defs": {
                "A": {
                    "$id": "child1",
                    "allOf": [
                        {
                            "$id": "child2",
                            "$anchor": "my_anchor",
                            "type": "number"
                        },
                        {
                            "$anchor": "my_anchor",
                            "type": "string"
                        }
                    ]
                }
            },
            "$ref": "child1#my_anchor"
        },
        "tests": [
            {
                "description": "$ref resolves to /$defs/A/allOf/1",
                "data": "a",
                "valid": true
            },
            {
                "description": "$ref does not resolve to /$defs/A/allOf/0",
                "data": 1,
                "valid": false
            }
        ]
    }
]
